/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardBody: typeof import('bootstrap-vue-next')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-next')['BCardHeader']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownForm: typeof import('bootstrap-vue-next')['BDropdownForm']
    BDropdownGroup: typeof import('bootstrap-vue-next')['BDropdownGroup']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    Change_Rate_Per_Time: typeof import('./src/components/Main_Sub_Component/Change_Rate_Per_Time.vue')['default']
    Chart: typeof import('./src/components/Main_Sub_Component/Chart.vue')['default']
    Chatting: typeof import('./src/components/Chatting/Chatting.vue')['default']
    Chatting_Input: typeof import('./src/components/Chatting/Chatting_Input.vue')['default']
    IBiArrowLeftCircleFill: typeof import('~icons/bi/arrow-left-circle-fill')['default']
    IBiArrowRightCircleFill: typeof import('~icons/bi/arrow-right-circle-fill')['default']
    IBiArrowUpCircleFill: typeof import('~icons/bi/arrow-up-circle-fill')['default']
    IBiBarChartFill: typeof import('~icons/bi/bar-chart-fill')['default']
    IBiBellFill: typeof import('~icons/bi/bell-fill')['default']
    IBiChatDotsFill: typeof import('~icons/bi/chat-dots-fill')['default']
    IBiChatRightDotsFill: typeof import('~icons/bi/chat-right-dots-fill')['default']
    IBiChevronDoubleDown: typeof import('~icons/bi/chevron-double-down')['default']
    IBiChevronDoubleLeft: typeof import('~icons/bi/chevron-double-left')['default']
    IBiGear: typeof import('~icons/bi/gear')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    Left_Bar: typeof import('./src/components/Left_Bar.vue')['default']
    Main_Page: typeof import('./src/components/Main_Page.vue')['default']
    Mobile_Header: typeof import('./src/components/Mobile_Header.vue')['default']
    Rapid_Change: typeof import('./src/components/Main_Sub_Component/Rapid_Change.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Trade_Checker: typeof import('./src/components/Main_Sub_Component/Trade_Checker.vue')['default']
  }
}
